-d D:\shen\3-code\ichip-code\final\Linux_Terminal_Code\impl\gwsynthesis\Linux_terminal.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst D:\shen\3-code\ichip-code\final\Linux_Terminal_Code\src\pins.cst
-cfg D:\shen\3-code\ichip-code\final\Linux_Terminal_Code\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
