iverilog -g2005-sv -o wave.out -I ../rtl/core ./sys_tb_top.sv ./gowin_sim_lib/gw2a/prim_sim.v ^
../rtl/core/e203_defines.v ^
../rtl/core/e203_biu.v ^
../rtl/core/e203_clk_ctrl.v ^
../rtl/core/e203_clkgate.v ^
../rtl/core/e203_clk_unit.v ^
../rtl/core/e203_core.v ^
../rtl/core/e203_cpu_top.v ^
../rtl/core/e203_cpu.v ^
../rtl/core/e203_dtcm_ctrl.v ^
../rtl/core/e203_dtcm_ram.v ^
../rtl/core/e203_extend_csr.v ^
../rtl/core/e203_exu_alu_bjp.v ^
../rtl/core/e203_exu_alu_csrctrl.v ^
../rtl/core/e203_exu_alu_dpath.v ^
../rtl/core/e203_exu_alu_lsuagu.v ^
../rtl/core/e203_exu_alu_muldiv.v ^
../rtl/core/e203_exu_alu_rglr.v ^
../rtl/core/e203_exu_alu.v ^
../rtl/core/e203_exu_branchslv.v ^
../rtl/core/e203_exu_commit.v ^
../rtl/core/e203_exu_csr.v ^
../rtl/core/e203_exu_decode.v ^
../rtl/core/e203_exu_disp.v ^
../rtl/core/e203_exu_excp.v ^
../rtl/core/e203_exu_longpwbck.v ^
../rtl/core/e203_exu_oitf.v ^
../rtl/core/e203_exu_regfile.v ^
../rtl/core/e203_exu.v ^
../rtl/core/e203_exu_wbck.v ^
../rtl/core/e203_ifu_ifetch.v ^
../rtl/core/e203_ifu_ift2icb.v ^
../rtl/core/e203_ifu_litebpu.v ^
../rtl/core/e203_ifu_minidec.v ^
../rtl/core/e203_ifu.v ^
../rtl/core/e203_irq_sync.v ^
../rtl/core/e203_itcm_ctrl.v ^
../rtl/core/e203_itcm_ram.v ^
../rtl/core/e203_lsu_ctrl.v ^
../rtl/core/e203_lsu.v ^
../rtl/core/e203_reset_ctrl.v ^
../rtl/core/e203_soc_demo.v ^
../rtl/core/e203_soc_top.v ^
../rtl/core/e203_srams.v ^
../rtl/core/e203_subsys_clint.v ^
../rtl/core/e203_subsys_gfcm.v ^
../rtl/core/e203_subsys_hclkgen_rstsync.v ^
../rtl/core/e203_subsys_hclkgen.v ^
../rtl/core/e203_subsys_main.v ^
../rtl/core/e203_subsys_mems.v ^
../rtl/core/e203_subsys_perips.v ^
../rtl/core/e203_subsys_plic.v ^
../rtl/core/e203_subsys_pllclkdiv.v ^
../rtl/core/e203_subsys_pll.v ^
../rtl/core/e203_subsys_top.v ^
../rtl/core/i2c_master_bit_ctrl.v ^
../rtl/core/i2c_master_byte_ctrl.v ^
../rtl/core/i2c_master_defines.v ^
../rtl/core/i2c_master_top.v ^
../rtl/core/sirv_1cyc_sram_ctrl.v ^
../rtl/core/sirv_aon_lclkgen_regs.v ^
../rtl/core/sirv_aon_porrst.v ^
../rtl/core/sirv_aon_top.v ^
../rtl/core/sirv_aon.v ^
../rtl/core/sirv_aon_wrapper.v ^
../rtl/core/sirv_AsyncResetReg.v ^
../rtl/core/sirv_AsyncResetRegVec_129.v ^
../rtl/core/sirv_AsyncResetRegVec_1.v ^
../rtl/core/sirv_AsyncResetRegVec_36.v ^
../rtl/core/sirv_AsyncResetRegVec_67.v ^
../rtl/core/sirv_AsyncResetRegVec.v ^
../rtl/core/sirv_clint_top.v ^
../rtl/core/sirv_clint.v ^
../rtl/core/sirv_debug_csr.v ^
../rtl/core/sirv_debug_module.v ^
../rtl/core/sirv_debug_ram.v ^
../rtl/core/sirv_debug_rom.v ^
../rtl/core/sirv_DeglitchShiftRegister.v ^
../rtl/core/sirv_expl_apb_slv.v ^
../rtl/core/sirv_expl_axi_slv.v ^
../rtl/core/sirv_flash_qspi_top.v ^
../rtl/core/sirv_flash_qspi.v ^
../rtl/core/sirv_gnrl_bufs.v ^
../rtl/core/sirv_gnrl_dffs.v ^
../rtl/core/sirv_gnrl_icbs.v ^
../rtl/core/sirv_gnrl_ram.v ^
../rtl/core/sirv_gnrl_xchecker.v ^
../rtl/core/sirv_gpio_top.v ^
../rtl/core/sirv_gpio.v ^
../rtl/core/sirv_hclkgen_regs.v ^
../rtl/core/sirv_icb1to16_bus.v ^
../rtl/core/sirv_icb1to2_bus.v ^
../rtl/core/sirv_icb1to8_bus.v ^
../rtl/core/sirv_jtag_dtm.v ^
../rtl/core/sirv_jtaggpioport.v ^
../rtl/core/sirv_LevelGateway.v ^
../rtl/core/sirv_mrom_top.v ^
../rtl/core/sirv_mrom.v ^
../rtl/core/sirv_otp_top.v ^
../rtl/core/sirv_plic_man.v ^
../rtl/core/sirv_plic_top.v ^
../rtl/core/sirv_pmu_core.v ^
../rtl/core/sirv_pmu.v ^
../rtl/core/sirv_pwm16_core.v ^
../rtl/core/sirv_pwm16_top.v ^
../rtl/core/sirv_pwm16.v ^
../rtl/core/sirv_pwm8_core.v ^
../rtl/core/sirv_pwm8_top.v ^
../rtl/core/sirv_pwm8.v ^
../rtl/core/sirv_pwmgpioport.v ^
../rtl/core/sirv_qspi_1cs_top.v ^
../rtl/core/sirv_qspi_1cs.v ^
../rtl/core/sirv_qspi_4cs_top.v ^
../rtl/core/sirv_qspi_4cs.v ^
../rtl/core/sirv_qspi_arbiter.v ^
../rtl/core/sirv_qspi_fifo.v ^
../rtl/core/sirv_qspi_media_1.v ^
../rtl/core/sirv_qspi_media_2.v ^
../rtl/core/sirv_qspi_media.v ^
../rtl/core/sirv_qspi_physical_1.v ^
../rtl/core/sirv_qspi_physical_2.v ^
../rtl/core/sirv_qspi_physical.v ^
../rtl/core/sirv_queue_1.v ^
../rtl/core/sirv_queue.v ^
../rtl/core/sirv_repeater_6.v ^
../rtl/core/sirv_ResetCatchAndSync_2.v ^
../rtl/core/sirv_ResetCatchAndSync.v ^
../rtl/core/sirv_rtc.v ^
../rtl/core/sirv_sim_ram.v ^
../rtl/core/sirv_spi_flashmap.v ^
../rtl/core/sirv_spigpioport_1.v ^
../rtl/core/sirv_spigpioport_2.v ^
../rtl/core/sirv_spigpioport.v ^
../rtl/core/sirv_sram_icb_ctrl.v ^
../rtl/core/sirv_tlfragmenter_qspi_1.v ^
../rtl/core/sirv_tl_repeater_5.v ^
../rtl/core/sirv_tlwidthwidget_qspi.v ^
../rtl/core/sirv_uartgpioport.v ^
../rtl/core/sirv_uartrx.v ^
../rtl/core/sirv_uart_top.v ^
../rtl/core/sirv_uarttx.v ^
../rtl/core/sirv_uart.v ^
../rtl/core/sirv_wdog.v ^

